---
acls:
- entries:
  - action: permit
    dstprefix: 10.0.0.0
    dstprefixlen: '24'
    protocol: ip
    seqno: 10
    srcprefix: 10.0.0.0
    srcprefixlen: '24'
  name: ACL-TEST-IN
  type: extended

ethernet:
- description: "CORE: to-r2-e1"
  et: '1'
  ipadd: 10.0.12.1
  iplen: '30'
  switchport: 'no'
- description: "CORE: to-r3-e1"
  et: '2'
  ipadd: 10.0.13.1
  iplen: '30'
  switchport: 'no'

prefixlists:
- entries:
  - action: permit
    prefix: 192.168.1.0
    prefixlen: '24'
    seqno: 10
  name: PL-TEST

routemaps:
- entries:
  - action: permit
    match: ip address prefix-list PL-TEST
    seqno: 10
    set: local-preference 150
  - action: deny
    seqno: 100
  name: RM-TEST-IN

staticroutes:
- name: TEST-STATIC-ROUTE
  nexthop: 10.0.12.2
  prefix: 11.11.11.11
  prefixlen: '32'
  tag: '1000'

bgp:
  asn: 100
  router_id: "10.0.0.1"
  maximum_paths: 2
  graceful_restart: "restart-time 300"
  groups:
    - name: "AS100-CORE"
      asn: 100
      next_hop_self: True
      update_source: "Loopback1"
      timers:
        hello: 2
        hold: 6
      additional_paths:
        - "receive"
        - "send any"
      password: "mpls-sr"
      send_community: "standard extended"
      maximum_routes: 0
  neighbors:
    - name: "10.0.0.2"
      group: "AS100-CORE"
      description: "R02"
    - name: "10.0.0.3"
      group: "AS100-CORE"
      description: "R03"
  address_family:
    - name: "evpn"
      default: "encapsulation mpls next-hop-self source-interface Loopback1"
      neighbors:
        - name: "10.0.0.2"
          status: "activate"
        - name: "10.0.0.3"
          status: "activate"
  vrf:
    - name: "CUST-A"
      rd: "100:1"
      route_target:
        import: "evpn 100:1"
        export: "evpn 100:1"
      network:
        - "192.168.0.1/32"

isis:
  name: "CORE"
  net: "49.0000.0001.0010.0000.0000.0001.00"
  level: "level-2"
  log_adj: "yes"
  overload_bit: "on-startup wait-for-bgp timeout 180"
  address_family:
    - name: "ipv4 unicast"
      bfd: "all-interfaces"
  sr:
    router_id: "10.0.0.1"
    shutdown: "no"
