---
ethernet:
- description: "CORE: to-r1-e2"
  et: '1'
  ipadd: 10.0.13.2
  iplen: '30'
  switchport: 'no'
- description: "CORE: to-r2-e2"
  et: '2'
  ipadd: 10.0.23.2
  iplen: '30'
  switchport: 'no'

bgp:
  asn: 100
  router_id: "10.0.0.3"
  maximum_paths: 2
  graceful_restart: "restart-time 300"
  groups:
    - name: "AS100-CORE"
      asn: 100
      next_hop_self: True
      update_source: "Loopback1"
      timers:
        hello: 2
        hold: 6
      additional_paths:
        - "receive"
        - "send any"
      password: "mpls-sr"
      send_community: "standard extended"
      maximum_routes: 0
  neighbors:
    - name: "10.0.0.1"
      group: "AS100-CORE"
      description: "R01"
    - name: "10.0.0.2"
      group: "AS100-CORE"
      description: "R02"
  address_family:
    - name: "evpn"
      default: "encapsulation mpls next-hop-self source-interface Loopback1"
      neighbors:
        - name: "10.0.0.1"
          status: "activate"
        - name: "10.0.0.2"
          status: "activate"
  vrf:
    - name: "CUST-A"
      rd: "100:1"
      route_target:
        import: "evpn 100:1"
        export: "evpn 100:1"
      network:
        - "192.168.0.3/32"
isis:
  name: "CORE"
  net: "49.0000.0001.0010.0000.0000.0003.00"
  level: "level-2"
  log_adj: "yes"
  overload_bit: "on-startup wait-for-bgp timeout 180"
  address_family:
    - name: "ipv4 unicast"
      bfd: "all-interfaces"
  sr:
    router_id: "10.0.0.3"
    shutdown: "no"

