---
- name: Gather show ip route
  hosts: ceoslab
  connection: httpapi
  gather_facts: false

  tasks:
    - name: Collect show ip route
      eos_command:
        commands:
          - command: show ip route vrf all
            output: json
            # although we are using the connection httpapi, somehow, the output of the commands is not in json format if you dont state it.
      register: routes_status

    - name: Display result
      debug:
        var: routes_status
