---
- name: Run commands on ceos lab via ssh
  hosts: ceoslab
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Collect all facts from device
      eos_facts:
        gather_subset:
          - all
      register: facts

    - name: Display result
      debug:
        msg: "Model is {{ facts.ansible_facts.ansible_net_model }} and it is running {{ facts.ansible_facts.ansible_net_version }}"
