---
- name: 1- CONTAINER TELEGRAF SYSLOG // CREATING FOLDER 
  file:
      dest: "{{ path_to_containers }}/{{ container_item }}"
      state: directory
  tags:
      - tag_syslog

- name: 2- CONTAINER TELEGRAF SYSLOG // GETTING IP OF INFLUXDB
  docker_container:
      name: influxdb
  become: yes
  register: influxdb_inspect
  tags:
      - tag_syslog

- name: 3- CONTAINER TELEGRAF SYSLOG // TEMPLATING TELEGRAF CONFIG
  template:
      src: "{{ container_item }}_template.j2"
      dest: "{{ path_to_containers }}/{{ container_item }}/telegraf.conf"
  tags:
      - tag_syslog

- name: 4- CONTAINER TELEGRAF SYSLOG // LAUNCHING CONTAINER
  docker_container:
      name: telegraf_syslog
      image: telegraf
      state: started
      command: "-config /etc/telegraf/telegraf.conf"
      networks:
          - name: "{{ docker_mon_net.name }}"
      purge_networks: yes
      ports:
          - "6514:6514/udp"
      volumes:
           - "{{ path_to_containers }}/{{ container_item }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
  become: yes
  tags:
      - tag_syslog
...
