---
- name: CREATING FOLDER FOR ALL CONTAINERS
  file:
      dest: "{{ path_to_containers }}"
      state: directory
  tags:
      - tag_install

- name: GETTING PWD
  command: pwd
  register: pwd
  tags:
      - tag_install

- name: SETTING PWD VARIABLE
  set_fact:
      pwd_actual: "{{ pwd.stdout }}"
  tags:
      - tag_install

- name: CREATING USER-DEFINED DOCKER NETWORK
  shell: "docker network create {{ docker_mon_net.name }} {% if docker_mon_net.subnet is defined %}--subnet {{ docker_mon_net.subnet }}{% endif %} {% if docker_mon_net.gateway is defined %}--gateway {{ docker_mon_net.gateway }}{% endif %}"
  ignore_errors: yes
  become: yes
  tags:
      - tag_install

- name: STARTING CONTAINERS
  include_tasks: container_{{ container_item }}.yml
  loop:
      - influxdb
      - grafana
      - telegraf_snmp
      - telegraf_syslog
  loop_control:
      loop_var: container_item
  tags:
      - tag_install
      - tag_grafana
      - tag_influx
      - tag_snmp
      - tag_syslog

- name: IPTABLES HACK
  shell: |
    iptables -t filter -D DOCKER-ISOLATION-STAGE-1 -j ACCEPT
    iptables -t filter -I DOCKER-ISOLATION-STAGE-1 -j ACCEPT
  ignore_errors: yes
  become: yes
  tags:
      - tag_install
...
